jobs:
  build:
    docker:
      - image: ubuntu:20.04

    steps:
      - run: apt update
      - run: apt install openjdk-8-jdk
  
  test:
    docker:
      - image: ubuntu:20.04

    steps:
      - run: java -version


workflows:
  version: 2

  build-and-test:
    jobs:
      - build
      - test:
        requires:
          - build

